<template>
  <section id="tools-section" class="pb-64">
    <h1 class="text-center text-4xl">Narzędzia</h1>
    <div
      class="flex items-center justify-center my-12 flex-wrap max-w-[1080px] mx-auto"
      data-aos="fade-left"
      data-aos-duration="1000"
    >
      <img
        class="m-3"
        src="./../../assets/img/home/tools/vscode.svg"
        alt="Visual Studio Code"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/redmine.jpg"
        alt="Redmine"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/mattermost.svg"
        alt="Mattermost"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/npm.svg"
        alt="npm"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/github.svg"
        alt="GitHub"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/gitlab.svg"
        alt="GitLab"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/adobeps.svg"
        alt="Adobe Photoshop"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/adobeai.svg"
        alt="Adobe Illustrator"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/adobexd.svg"
        alt="Adobe XD"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/figma.svg"
        alt="Figma"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/webpack.svg"
        alt="webpack"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/netlify.svg"
        alt="netlify"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/heroku.svg"
        alt="heroku"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/IntelliJ_IDEA.svg"
        alt="IntelliJ IDEA"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/eclipse.svg"
        alt="Eclipse"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/trello.svg"
        alt="Trello"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/grafana.svg"
        alt="Grafana"
        width="80"
        height="80"
      />
      <img
        class="m-3"
        src="./../../assets/img/home/tools/kibana.svg"
        alt="Kibana"
        width="80"
        height="80"
      />
    </div>
  </section>
</template>

<style scoped></style>
